pipeline:
  unit-tests:
    image: go
    commands:
      # - pip install -r requirements/development.txt
      # - DATABASE_URI=sqlite:///db.sqlite3 py.test -s -vv
    # TODO: Add codacy, codeclimate, codedev and sentry to app
    # secrets: [ codacy_token, codeclimate_token, codecov_token ]
    when:
      event: [push, tag]

  staging-publish:
    image: plugins/docker
    repo: nossas/bonde-imaginary
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]


  production-publish:
    image: plugins/docker
    repo: nossas/bonde-imaginary
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]

